const DOLAPY_STORE='dolapy.pages.v3';
const BG_URL='https://cdn.jsdelivr.net/npm/@imgly/background-removal@1.7.0/+esm';
const TF_URL='https://cdn.jsdelivr.net/npm/@huggingface/transformers@4.2.0';
const FASHION_MODEL='ff13/fashion-clip';
let aiBg=null,aiClassifier=null,aiLoading=null,aiQueue=[],aiCurrent=null,cameraStream=null;
const q=s=>document.querySelector(s);
const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const COLORS={black:['black','charcoal','graphite','onyx'],white:['white','cream','ivory'],grey:['grey','gray','silver'],neutral:['beige','tan','camel','khaki','sand','stone','oat'],brown:['brown','chocolate','mocha','coffee'],blue:['navy','blue','denim','cobalt','teal','sky','azure'],green:['green','olive','sage','forest','mint'],red:['red','burgundy','maroon','wine','crimson'],orange:['orange','rust','terracotta','coral'],yellow:['yellow','mustard','gold'],purple:['purple','lavender','lilac','violet'],pink:['pink','rose','blush']};
const CATEGORY_LABELS=['t-shirt','shirt','polo shirt','hoodie','sweater','cardigan','jacket','coat','blazer','overshirt','jeans','trousers','cargo pants','chinos','shorts','skirt','dress','suit','sneakers','boots','loafers','sandals','heels','bag','backpack','cap','hat','belt','watch','scarf','glasses'];
const STYLE_LABELS=['casual','streetwear','smart','athletic','utility','minimal','preppy','vintage'];
function familyColor(v){const s=String(v||'').toLowerCase();for(const[k,w]of Object.entries(COLORS))if(w.some(x=>s.includes(x)))return k;return'';}
function title(s){return s.replace(/(^|[\s-])([a-z])/g,(m,p,c)=>p+c.toUpperCase());}
function categoryFor(label,name){const s=(label+' '+name).toLowerCase();if(/dress/.test(s))return'dresses';if(/jeans|trouser|cargo|chino|shorts|skirt|pants/.test(s))return'bottoms';if(/sneaker|boot|loafer|sandal|heel/.test(s))return'shoes';if(/jacket|coat|blazer|overshirt|hoodie|sweater|cardigan|suit/.test(s))return'outerwear';if(/bag|backpack|cap|hat|belt|watch|scarf|glasses/.test(s))return'accessories';return'tops';}
function inferStyle(name){const s=name.toLowerCase();if(/street|oversized|graphic|skater|baggy|cargo/.test(s))return'streetwear';if(/formal|tailored|blazer|office|dressy|oxford/.test(s))return'smart';if(/sport|gym|active|running|trainer/.test(s))return'athletic';if(/utility|workwear|military/.test(s))return'utility';if(/vintage|retro|heritage|washed/.test(s))return'vintage';if(/minimal|clean|simple|plain/.test(s))return'minimal';if(/preppy|polo|varsity|classic/.test(s))return'preppy';return'casual';}
function silhouette(name){const s=name.toLowerCase();if(/oversized|boxy|baggy/.test(s))return'oversized';if(/wide|relaxed/.test(s))return'relaxed';if(/slim|skinny|tapered|fitted/.test(s))return'slim';return'regular';}
function pattern(name){const s=name.toLowerCase();if(/stripe/.test(s))return'stripe';if(/check|plaid/.test(s))return'check';if(/graphic/.test(s))return'graphic';if(/print|floral/.test(s))return'print';return'solid';}
function rgbFamily(r,g,b){const mx=Math.max(r,g,b),mn=Math.min(r,g,b),d=mx-mn;if(mx<55)return'black';if(mx>232&&d<25)return'white';if(d<18&&mx<165)return'grey';const nr=r/255,ng=g/255,nb=b/255,h=(Math.atan2(Math.sqrt(3)*(ng-nb),2*nr-ng-nb)*180/Math.PI+360)%360;if((h<18||h>=345)&&r>g*1.18)return'red';if(h>=18&&h<48)return'orange';if(h>=48&&h<75)return'yellow';if(h>=75&&h<165)return'green';if(h>=165&&h<255)return'blue';if(h>=255&&h<310)return'purple';if(h>=310&&h<345)return'pink';if(mx<205&&r>g*1.08&&r>b*1.08)return'brown';if(mx<205)return'neutral';return'';}
function detectColor(dataUrl){return new Promise(resolve=>{const img=new Image();img.onload=()=>{try{const c=document.createElement('canvas');c.width=c.height=96;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0,96,96);const d=ctx.getImageData(8,8,80,80).data;let r=0,g=0,b=0,n=0;for(let i=0;i<d.length;i+=4){if(d[i+3]<90)continue;const mx=Math.max(d[i],d[i+1],d[i+2]),mn=Math.min(d[i],d[i+1],d[i+2]);if(mx-mn<8&&mx>190)continue;r+=d[i];g+=d[i+1];b+=d[i+2];n++;}resolve(n?rgbFamily(r/n,g/n,b/n):'');}catch{resolve('');}};img.onerror=()=>resolve('');img.src=dataUrl;});}
function blobData(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(blob);});}
function compress(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=reject;r.onload=()=>{const img=new Image();img.onload=()=>{const m=1400,s=Math.min(1,m/Math.max(img.naturalWidth,img.naturalHeight)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.naturalWidth*s));c.height=Math.max(1,Math.round(img.naturalHeight*s));c.getContext('2d').drawImage(img,0,0,c.width,c.height);c.toBlob(b=>b?resolve(b):reject(new Error('encode')),'image/jpeg',.86);};img.onerror=reject;img.src=r.result;};r.readAsDataURL(file);});}
function scanUI(){let el=q('#aiScanStatus');if(el)return el;el=document.createElement('div');el.id='aiScanStatus';el.className='scan-status';el.hidden=true;el.innerHTML='<div class="scan-card"><div class="scan-spinner"></div><div class="scan-copy"><strong id="aiScanLabel">Preparing AI…</strong><span id="aiScanSub">Removing background and understanding your piece.</span></div><div class="scan-track"><span id="aiScanBar"></span></div></div>';document.body.appendChild(el);return el;}
function scan(show,label,pct,sub){const el=scanUI();el.hidden=!show;if(show){q('#aiScanLabel').textContent=label;q('#aiScanSub').textContent=sub||'Running privately in your browser.';q('#aiScanBar').style.width=`${pct}%`;}}
async function loadAI(){if(aiLoading)return aiLoading;aiLoading=(async()=>{scan(true,'Loading background remover…',8,'The first scan downloads the vision models.');const bg=await import(BG_URL);aiBg=bg.removeBackground;scan(true,'Loading fashion recognition…',22,'After this first load, the browser can cache the model.');const t=await import(TF_URL);aiClassifier=await t.pipeline('zero-shot-image-classification',FASHION_MODEL,{dtype:'q8'});scan(true,'AI ready',100,'Ready to isolate and identify clothing.');})();return aiLoading;}
async function analyse(file){const original=await compress(file);let cutout=original;scan(true,'Removing background…',34,'Isolating only the clothing piece.');try{await loadAI();cutout=await aiBg(original,{model:'isnet_quint8',output:{format:'image/webp',quality:.88},progress:(k,c,t)=>scan(true,'Removing background…',34+Math.round(c/Math.max(t,1)*30),'Cleaning the edges around the garment.'));}catch(e){console.warn('background removal',e);}const data=await blobData(cutout);let label='clothing',style='casual',confidence=.2;try{scan(true,'Identifying the piece…',72,'Fashion vision is comparing the photo with clothing categories.');const u=URL.createObjectURL(cutout);const r=await aiClassifier(u,CATEGORY_LABELS);URL.revokeObjectURL(u);if(r?.[0]){label=r[0].label;confidence=r[0].score||.2;}scan(true,'Reading the style…',84,'Checking the visual style family.');const sr=await aiClassifier(data,STYLE_LABELS);if(sr?.[0])style=sr[0].label;}catch(e){console.warn('fashion classifier',e);}scan(true,'Naming the piece…',94,'Creating a useful wardrobe name.');const fileName=file.name.replace(/\.[^/.]+$/,'').replace(/[-_]+/g,' ').trim();const category=confidence>.12?categoryFor(label,fileName):categoryFor('',fileName);const color=(await detectColor(data))||familyColor(fileName);const shape=silhouette(fileName);const pretty=title(label==='clothing'?(category==='tops'?'top':category==='bottoms'?'bottom':category):label);const name=title([color,style!=='casual'?style:'',pretty].filter(Boolean).join(' '));return{id:uid(),name,image:data,category,color,style,season:/summer|linen|tank|shorts|sandal|tee/.test((fileName+' '+label).toLowerCase())?'summer':/winter|wool|coat|puffer|fleece|knit/.test((fileName+' '+label).toLowerCase())?'winter':'all',occasion:style==='smart'?'smart':style==='athletic'?'sport':'everyday',silhouette:shape,pattern:pattern(fileName),warmth:category==='outerwear'?4:category==='shoes'?2:3,formality:style==='smart'?4:style==='preppy'?3:style==='athletic'?1:2,wearCount:0,favorite:false,metadataConfidence:clamp01(confidence),aiIdentified:confidence>.12,createdAt:Date.now()};}
function clamp01(n){return Math.max(.2,Math.min(1,Number(n)||.2));}
function openResult(item,queueText){aiCurrent=item;if(q('#previewImg'))q('#previewImg').src=item.image;if(q('#fName'))q('#fName').value=item.name;if(q('#fCategory'))q('#fCategory').value=item.category;if(q('#fColor'))q('#fColor').value=item.color;if(q('#fStyle'))q('#fStyle').value=item.style;if(q('#queueInfo'))q('#queueInfo').textContent=queueText||'AI identified · background removed';if(q('#modal'))q('#modal').hidden=false;}
function nextResult(){if(!aiQueue.length){scan(false);aiCurrent=null;return;}openResult(aiQueue.shift(),aiQueue.length?`${aiQueue[0].queueIndex} of ${aiQueue[0].queueTotal} pieces next`:'AI identified · background removed');}
function saveResult(){if(!aiCurrent)return;aiCurrent.name=String(q('#fName').value||'').trim()||aiCurrent.name;aiCurrent.category=q('#fCategory').value;aiCurrent.color=String(q('#fColor').value||'').trim();aiCurrent.style=q('#fStyle').value;aiCurrent.formality=aiCurrent.style==='smart'?4:aiCurrent.style==='preppy'?3:aiCurrent.style==='athletic'?1:2;let items;try{items=JSON.parse(localStorage.getItem(DOLAPY_STORE)||'[]');}catch{items=[];}if(!Array.isArray(items))items=[];items.unshift(aiCurrent);try{localStorage.setItem(DOLAPY_STORE,JSON.stringify(items));}catch{alert('Wardrobe storage is full. Remove an older piece first.');return;}q('#modal').hidden=true;aiCurrent=null;if(aiQueue.length)nextResult();else{scan(false);location.reload();}}
async function startAIUpload(files){const list=[...(files||[])].filter(f=>f.type?.startsWith('image/'));if(!list.length)return;try{aiQueue=[];for(let i=0;i<list.length;i++){const item=await analyse(list[i]);item.queueIndex=i+1;item.queueTotal=list.length;aiQueue.push(item);}scan(false);nextResult();}catch(e){console.error(e);scan(false);alert('Could not analyze that photo. Try one clear clothing piece against a simple background.');}}
async function startCamera(){q('#cameraModal').hidden=false;try{cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:1280}},audio:false});q('#cameraVideo').srcObject=cameraStream;}catch(e){console.error(e);q('#cameraNote').textContent='Camera permission was blocked. Use Choose from device instead.';}}
function stopCamera(){if(cameraStream){cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null;}if(q('#cameraVideo'))q('#cameraVideo').srcObject=null;}
function closeCamera(){stopCamera();q('#cameraModal').hidden=true;}
async function capture(){const video=q('#cameraVideo');if(!video.videoWidth){alert('Camera is not ready yet.');return;}const c=q('#cameraCanvas'),m=1400,s=Math.min(1,m/Math.max(video.videoWidth,video.videoHeight));c.width=Math.round(video.videoWidth*s);c.height=Math.round(video.videoHeight*s);c.getContext('2d').drawImage(video,0,0,c.width,c.height);const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.9));if(!blob)return;closeCamera();await startAIUpload([new File([blob],`dolapy-${Date.now()}.jpg`,{type:'image/jpeg'})]);}
function bind(){['addHeroAI','addWardrobeAI','bottomAddAI'].forEach(id=>document.addEventListener('click',e=>{if(e.target.closest('#'+id))startCamera();}));if(q('#cameraGallery'))q('#cameraGallery').addEventListener('click',()=>{closeCamera();q('#aiFileInput').click();});if(q('#closeCamera'))q('#closeCamera').addEventListener('click',closeCamera);if(q('#capturePhoto'))q('#capturePhoto').addEventListener('click',capture);if(q('#closeModal'))q('#closeModal').addEventListener('click',()=>{q('#modal').hidden=true;aiQueue=[];aiCurrent=null;scan(false);});if(q('#saveItem'))q('#saveItem').addEventListener('click',saveResult);q('#aiFileInput').addEventListener('change',e=>{const fs=e.target.files;e.target.value='';startAIUpload(fs);});document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(q('#cameraModal')&&!q('#cameraModal').hidden)closeCamera();else if(q('#modal')&&!q('#modal').hidden){q('#modal').hidden=true;aiQueue=[];aiCurrent=null;scan(false);}}});window.addEventListener('beforeunload',stopCamera);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
