(()=>{
'use strict';
const $=s=>document.querySelector(s);let stream=null;
const isMobile=()=>/Android|iPhone|iPad|iPod|Mobile/i.test(navigator.userAgent||'')||Boolean(globalThis.matchMedia?.('(pointer: coarse)')?.matches);
function getPhotoInput(){const i=$('#aiFileInput');if(!i)return null;i.accept='image/*';if(isMobile())i.setAttribute('capture','environment');return i}
function sendToVision(files){const list=[...(files||[])].filter(f=>f?.type?.startsWith('image/'));if(!list.length)return;if(typeof globalThis.startAIUpload==='function'){Promise.resolve(globalThis.startAIUpload(list)).catch(e=>{console.error('Dolapy vision processing failed:',e);alert('Dolapy could not process that photo. Please try another photo.')});return}alert('Dolapy vision is still loading. Please try the photo again.')}
function nativePhoto(){globalThis.warmDolapyAI?.();const i=getPhotoInput();if(!i){alert('Camera input is unavailable. Please reload Dolapy.');return}i.value='';i.click()}
function stopCamera(){stream?.getTracks?.().forEach(t=>t.stop());stream=null;const v=$('#cameraVideo');if(v)v.srcObject=null}
function closeCamera(){stopCamera();const m=$('#cameraModal');if(m)m.hidden=true}
async function openCamera(){globalThis.warmDolapyAI?.();if(isMobile()){nativePhoto();return}const m=$('#cameraModal'),v=$('#cameraVideo');if(!m||!v||!navigator.mediaDevices?.getUserMedia){nativePhoto();return}m.hidden=false;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:1280},frameRate:{ideal:24,max:30}},audio:false});v.srcObject=stream;await v.play()}catch(e){console.warn('Dolapy camera failed; using native photo capture:',e);closeCamera();nativePhoto()}}
async function captureDesktop(){const v=$('#cameraVideo'),c=$('#cameraCanvas');if(!v||!c||v.readyState<2||!v.videoWidth){nativePhoto();return}const max=1024,s=Math.min(1,max/Math.max(v.videoWidth,v.videoHeight));c.width=Math.max(1,Math.round(v.videoWidth*s));c.height=Math.max(1,Math.round(v.videoHeight*s));const x=c.getContext('2d');if(!x){nativePhoto();return}x.drawImage(v,0,0,c.width,c.height);const b=await new Promise(r=>c.toBlob(r,'image/jpeg',.92));if(!b){nativePhoto();return}const f=new File([b],`dolapy-${Date.now()}.jpg`,{type:'image/jpeg'});closeCamera();sendToVision([f])}
function bind(){getPhotoInput()?.addEventListener('change',e=>{e.stopImmediatePropagation();const f=[...(e.target.files||[])];e.target.value='';sendToVision(f)},true);for(const id of ['#addHeroAI','#addWardrobeAI','#bottomAddAI'])$(id)?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();openCamera()},true);$('#capturePhoto')?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();captureDesktop()},true);$('#closeCamera')?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();closeCamera()},true);$('#cameraGallery')?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();nativePhoto()},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();