(()=>{
'use strict';
const STORE='dolapy.pages.v3';
const BG_URL='https://esm.sh/@imgly/background-removal@1.7.0';
const BG_PUBLIC_PATH='https://staticimgly.com/@imgly/background-removal-data/1.7.0/dist/';
const $=s=>document.querySelector(s);
let removeBackground=null,loadPromise=null,current=null;
const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;
const title=s=>String(s||'').replace(/(^|[\s-])([a-z])/g,(m,p,c)=>p+c.toUpperCase());
const setStatus=(show,label='',sub='')=>{let e=$('#aiScanStatus');if(!e){e=document.createElement('div');e.id='aiScanStatus';e.className='scan-status';e.hidden=true;e.innerHTML='<div class="scan-card"><div class="scan-spinner"></div><div class="scan-copy"><strong id="aiScanLabel"></strong><span id="aiScanSub"></span></div></div>';document.body.appendChild(e)}e.hidden=!show;if(show){$('#aiScanLabel').textContent=label;$('#aiScanSub').textContent=sub)}};
const wait=(ms,msg)=>new Promise((_,rej)=>setTimeout(()=>rej(new Error(msg)),ms));
const withTimeout=(p,ms,msg)=>Promise.race([p,wait(ms,msg)]);
async function load(){if(loadPromise)return loadPromise;loadPromise=(async()=>{const m=await import(BG_URL);removeBackground=m.removeBackground||m.default||null;if(!removeBackground)throw new Error('IMG.LY export unavailable');return true})().catch(e=>{loadPromise=null;throw e});return loadPromise}
async function gpu(){try{return !!(navigator.gpu&&await navigator.gpu.requestAdapter())}catch{return false}}
function read(file){return new Promise((res,rej)=>{const r=new FileReader();r.onerror=()=>rej(new Error('Read failed'));r.onload=()=>res(r.result);r.readAsDataURL(file)})}
function img(src){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=()=>rej(new Error('Image decode failed'));i.src=src})}
async function normalize(file){const data=await read(file),i=await img(data),max=768,s=Math.min(1,max/Math.max(i.naturalWidth,i.naturalHeight)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(i.naturalWidth*s));c.height=Math.max(1,Math.round(i.naturalHeight*s));c.getContext('2d').drawImage(i,0,0,c.width,c.height);return new Promise((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error('Image encode failed')),'image/jpeg',.9))}
async function restoreRGB(original,result){const [a,b]=await Promise.all([img(await read(original)),img(await read(result))]),w=b.naturalWidth,h=b.naturalHeight,oc=document.createElement('canvas'),rc=document.createElement('canvas');oc.width=rc.width=w;oc.height=rc.height=h;const ox=oc.getContext('2d',{willReadFrequently:true}),rx=rc.getContext('2d',{willReadFrequently:true,alpha:true});ox.drawImage(a,0,0,w,h);rx.drawImage(b,0,0,w,h);const od=ox.getImageData(0,0,w,h).data,rd=rx.getImageData(0,0,w,h),px=rd.data;for(let i=0;i<px.length;i+=4){px[i]=od[i];px[i+1]=od[i+1];px[i+2]=od[i+2]}const out=document.createElement('canvas');out.width=w;out.height=h;out.getContext('2d',{alpha:true}).putImageData(rd,0,0);return new Promise((res,rej)=>out.toBlob(x=>x?res(x):rej(new Error('PNG encode failed')),'image/png',1))}
async function valid(blob){const i=await img(await read(blob)),c=document.createElement('canvas');c.width=c.height=64;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(i,0,0,64,64);const d=x.getImageData(0,0,64,64).data;let t=0;for(let k=3;k<d.length;k+=4)if(d[k]<64)t++;return t/(64*64)>=.02}
async function cutout(blob){await load();const useGpu=await gpu();const primary=useGpu?{model:'isnet_fp16',device:'gpu'}:{model:'isnet_quint8',device:'cpu'};const fallback=useGpu?{model:'isnet_quint8',device:'cpu'}:null;setStatus(true,'Removing background…',useGpu?'Using GPU acceleration.':'Using compatible CPU model.');let out;try{out=await withTimeout(removeBackground(blob,{...primary,publicPath:BG_PUBLIC_PATH,proxyToWorker:false,output:{format:'image/png',quality:1}}),useGpu?70000:120000,'Background removal timed out')}catch(e){if(!fallback)throw e;setStatus(true,'Retrying cutout…','Switching to the compatible CPU model.');out=await withTimeout(removeBackground(blob,{...fallback,publicPath:BG_PUBLIC_PATH,proxyToWorker:false,output:{format:'image/png',quality:1}}),140000,'Background removal failed')}if(!out||!(await valid(out)))throw new Error('Background mask was not valid');return restoreRGB(blob,out)}
function meta(file){const text=file.name.replace(/\.[^/.]+$/,'').replace(/[-_]+/g,' ').trim();const s=text.toLowerCase();let category='tops';if(/dress/.test(s))category='dresses';else if(/jeans|trouser|cargo|chino|shorts|skirt|pants/.test(s))category='bottoms';else if(/shoe|sneaker|boot|loafer|sandal|heel|slide/.test(s))category='shoes';else if(/jacket|coat|blazer|overshirt|hoodie|sweater|cardigan|suit/.test(s))category='outerwear';else if(/bag|backpack|cap|hat|belt|watch|scarf|glasses/.test(s))category='accessories';let style='casual';if(/cargo|hoodie|jacket|overshirt|graphic|wide-leg/.test(s))style='streetwear';else if(/blazer|loafer|oxford|suit|tailored|formal/.test(s))style='smart';else if(/sport|running|trainer|gym|athletic/.test(s))style='athletic';else if(/utility|workwear/.test(s))style='utility';else if(/vintage|retro|heritage|washed/.test(s))style='vintage';else if(/polo|classic|varsity/.test(s))style='preppy';else if(/minimal|plain|clean/.test(s))style='minimal';return{id:uid(),name:title(text||category),image:'',category,style,color:'',season:'all',occasion:style==='smart'?'smart':style==='athletic'?'sport':'everyday',silhouette:/oversized|boxy|baggy/.test(s)?'oversized':/wide|relaxed/.test(s)?'relaxed':/slim|skinny|tapered/.test(s)?'slim':'regular',pattern:'solid',warmth:category==='outerwear'?4:category==='shoes'?2:3,formality:style==='smart'?4:style==='preppy'?3:style==='athletic'?1:2,wearCount:0,favorite:false,createdAt:Date.now(),backgroundRemoved:true}}
function open(item){current=item;$('#previewImg').src=item.image;$('#fName').value=item.name;$('#fCategory').value=item.category;$('#fColor').value=item.color;$('#fStyle').value=item.style;$('#queueInfo').textContent='On-device cutout complete. Review and save.';$('#modal').hidden=false}
function close(){current=null;$('#modal').hidden=true;setStatus(false)}
function save(e){if(!current)return;e.preventDefault();e.stopImmediatePropagation();const item={...current,name:($('#fName').value||current.name).trim(),category:$('#fCategory').value,color:($('#fColor').value||'').trim(),style:$('#fStyle').value,formality:$('#fStyle').value==='smart'?4:$('#fStyle').value==='preppy'?3:$('#fStyle').value==='athletic'?1:2};let items=[];try{items=JSON.parse(localStorage.getItem(STORE)||'[]')}catch{}items.unshift(item);localStorage.setItem(STORE,JSON.stringify(items));document.dispatchEvent(new CustomEvent('dolapy:items-changed'));close();window.showWardrobe?.();window.renderAll?.()}
async function process(file){setStatus(true,'Preparing photo…','Optimizing the image locally.');const normalized=await normalize(file),item=meta(file);setStatus(true,'Removing background…','Your photo stays on this device.');const png=await cutout(normalized);item.image=await read(png);open(item);setStatus(false)}
window.startAIUpload=async files=>{const list=[...(files||[])].filter(f=>f?.type?.startsWith('image/'));if(!list.length)return;try{await process(list[0])}catch(e){console.error('[Dolapy] fast vision:',e);setStatus(false);alert(`Dolapy could not remove the background: ${e.message}. Please retry with one garment centered in the frame.`)}};
window.DolapyFastVision={cutout,load};
document.addEventListener('click',e=>{if(e.target.closest('#saveItem'))save(e)},{capture:true});document.addEventListener('click',e=>{if(e.target.closest('#closeModal')){e.preventDefault();e.stopImmediatePropagation();close()}},{capture:true});
})();